# ======================
# BASE DE DONN?ES
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/security_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate 6: MySQLDialect convient (ou MySQL8Dialect)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ======================
# SERVEUR
# ======================
server.port=8080

# ======================
# MAIL (Gmail SMTP)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=allaye35@gmail.com
# Utilise un "App Password" Gmail (16 caract?res) :
spring.mail.password=aroy grec ybgo afqu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=8000
spring.mail.properties.mail.smtp.writetimeout=8000

# Adresse d?exp?diteur par d?faut pour tes mails applicatifs (optionnel)
# Utilise-la dans ton service d?email avec message.setFrom(...)
app.mail.from=Boulevard S?curit? <allaye35@gmail.com>

# ======================
# SMS (Textbelt)
# ======================
textbelt.api.key=textbelt

# ======================
# JOURS F?RI?S
# ======================
feries.base-url=https://calendrier.api.gouv.fr/jours-feries
feries.zone=metropole
feries.timeout-ms=2500
feries.cache-years=5

# ======================
# JWT
# ======================
security.jwt.secret=${JWT_SECRET:change-me-please-change-me-32-bytes-min}
# 2 heures en millisecondes
security.jwt.access-token-validity-ms=7200000
# 30 jours en millisecondes
security.jwt.refresh-token-validity-ms=2592000000

# ======================
# APP
# ======================
# URL publique utilis?e pour fabriquer les liens envoy?s par e-mail.
# - Mets l?URL du FRONT si tu veux rediriger vers l?appli React (ex: http://localhost:3000)
# - Laisse le backend si tu utilises des endpoints REST pour confirmer/renitialiser.
#app.public-url=http://localhost:8080
app.public-url=http://localhost:3000

# Dur?es d?expiration des tokens (heures)
app.email.verification.expiration-hours=24
app.password.reset.expiration-hours=2

# ======================
# JACKSON / DATES
# ======================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# ======================
# LOGS
# ======================
logging.level.org.hibernate.SQL=DEBUG
# Dur?e de vie du code OTP (en minutes)
app.email.verification.otp-expiration-minutes=15
# pour voir pourquoi ?a bloque si ?a rebloque
logging.level.org.springframework.security=DEBUG