# Configuration H2 (base en mémoire, supprimée à l'arrêt)
spring.datasource.url=jdbc:h2:mem:security_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Console H2 activée
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Port de l'application
server.port=8080
